### ISSUE TITLE
Mocking CouchDB examples

### ISSUE THREAD

**Issue by sankethpb** [go-kivik/kivik#318]
Could you please provide some examples on how to mock the database for unit testing purpose?

**Comment by flimzy** [comment]
There is no standard way to do this. It is in principle possible to create a mock driver (similar to the way [go-sqlmock](https://github.com/DATA-DOG/go-sqlmock) works for mocking SQL databases), but to my knowledge none currently exists.

There is also the [memorydb](https://github.com/go-kivik/memorydb) driver, which uses a temporary, in-memory data store, and may be useful for some tests, but it is very incomplete.

So that really leaves you probably doing your own mocking. You are welcome to view the [mock](https://github.com/go-kivik/kivik/tree/master/mock) directory used by this package for some possible examples, but this is not meant as a publicly-consumable library, so will change without notice, and is in no way expected to represent "best practice".

**Comment by sankethpb** [comment]
Would testify (https://github.com/stretchr/testify) be a good option?

**Comment by flimzy** [comment]
I have no opinion on testify's Mock capabilities, as I've never used it. I'm sure whether it is "good" is as subjective as any other opinion.

**Comment by sankethpb** [comment]
thank you

**Comment by kontrollanten** [comment]
Thanks for a great package! Would it be possible to create interfaces to make it possible to use [gomock](https://github.com/golang/mock) to autogenerate mocks? I'm new into Go and don't know the best practices in mocking and testing, but if you think interfaces is a good way to go I'd be happy to do a PR.

**Comment by patgrasso** [comment]
Actually, I take that back. It seems like the structs exported by the top-level package don't exactly line up with those `driver` interfaces. It _would_ be nice to have an easy way to mock instances of things like `kivik.DB` that doesn't involve creating an entire `driver` implementation to mock a single method, even if it means just creating interfaces for the top-level structs and exporting those rather than the structs themselves.
@kontrollanten

**Comment by flimzy** [comment]
I have recently begun work on a proper mock client for Kivik. It's still very much a work-in-progress, but anyone interested can follow the progress here: https://github.com/go-kivik/kivikmock
